//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathInput.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathInput.Resources.Language", typeof(Language).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the donation amount.
        /// </summary>
        public static string AmountPlaceholder {
            get {
                return ResourceManager.GetString("AmountPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Input.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DisplayAlertFailed {
            get {
                return ResourceManager.GetString("DisplayAlertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please checkout your Inputs.
        /// </summary>
        public static string DisplayAlertFailedMessage {
            get {
                return ResourceManager.GetString("DisplayAlertFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation Copied.
        /// </summary>
        public static string DisplayAlertMessage {
            get {
                return ResourceManager.GetString("DisplayAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DisplayAlertOK {
            get {
                return ResourceManager.GetString("DisplayAlertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string DisplayAlertSuccess {
            get {
                return ResourceManager.GetString("DisplayAlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string EmailSend {
            get {
                return ResourceManager.GetString("EmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your equation.
        /// </summary>
        public static string EntryPlaceholder {
            get {
                return ResourceManager.GetString("EntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixes.
        /// </summary>
        public static string FeedbackItem1 {
            get {
                return ResourceManager.GetString("FeedbackItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvements.
        /// </summary>
        public static string FeedbackItem2 {
            get {
                return ResourceManager.GetString("FeedbackItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string FeedbackItem3 {
            get {
                return ResourceManager.GetString("FeedbackItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string FeedbackItem4 {
            get {
                return ResourceManager.GetString("FeedbackItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ckannan759153@gmail.com.
        /// </summary>
        public static string FeedbackMail {
            get {
                return ResourceManager.GetString("FeedbackMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation from Image.
        /// </summary>
        public static string ImageOCR {
            get {
                return ResourceManager.GetString("ImageOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculus Statistics Symbols.
        /// </summary>
        public static string labelCalculusStatistics {
            get {
                return ResourceManager.GetString("labelCalculusStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Arithmetic and Algebra Symbols.
        /// </summary>
        public static string labelCommonArith {
            get {
                return ResourceManager.GetString("labelCommonArith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Statistics Symbols.
        /// </summary>
        public static string labelCommonStatistics {
            get {
                return ResourceManager.GetString("labelCommonStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Equivalence and Proportion Operators.
        /// </summary>
        public static string labelEquivalence_Proportion {
            get {
                return ResourceManager.GetString("labelEquivalence_Proportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction Symbols.
        /// </summary>
        public static string labelFraction {
            get {
                return ResourceManager.GetString("labelFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Symbols.
        /// </summary>
        public static string labelGeometric {
            get {
                return ResourceManager.GetString("labelGeometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Symbols.
        /// </summary>
        public static string labelLetter {
            get {
                return ResourceManager.GetString("labelLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Proofs Symbols.
        /// </summary>
        public static string labelLogical_Proofs {
            get {
                return ResourceManager.GetString("labelLogical_Proofs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic and Set Theory Symbols.
        /// </summary>
        public static string labelLogicSet {
            get {
                return ResourceManager.GetString("labelLogicSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Symbols.
        /// </summary>
        public static string labelMeasurement {
            get {
                return ResourceManager.GetString("labelMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Mathematical Symbols.
        /// </summary>
        public static string labelOther_Mathematical {
            get {
                return ResourceManager.GetString("labelOther_Mathematical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscripts Symbols.
        /// </summary>
        public static string labelSubscripts {
            get {
                return ResourceManager.GetString("labelSubscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscripts Symbols.
        /// </summary>
        public static string labelSuperscripts {
            get {
                return ResourceManager.GetString("labelSuperscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string layout1_labelText {
            get {
                return ResourceManager.GetString("layout1_labelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Type.
        /// </summary>
        public static string layout2_labelText {
            get {
                return ResourceManager.GetString("layout2_labelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string layout3_labelText {
            get {
                return ResourceManager.GetString("layout3_labelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Amount.
        /// </summary>
        public static string layout4_labelText {
            get {
                return ResourceManager.GetString("layout4_labelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math Input.
        /// </summary>
        public static string MathInput {
            get {
                return ResourceManager.GetString("MathInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Input.
        /// </summary>
        public static string NormalInput {
            get {
                return ResourceManager.GetString("NormalInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ToolbarClear {
            get {
                return ResourceManager.GetString("ToolbarClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ToolbarCopy {
            get {
                return ResourceManager.GetString("ToolbarCopy", resourceCulture);
            }
        }
    }
}
